/**
 * Quick test script — sends a dummy analytics report via WhatsApp.
 * Usage:  node test_whatsapp.js
 * On first run you must scan the QR code with WhatsApp.
 */
import pkg from 'whatsapp-web.js';
const { Client, LocalAuth } = pkg;
import qrcode from 'qrcode-terminal';

const PHONE = '918101402916';   // target number with country code
const CHAT_ID = PHONE + '@c.us';

// Dummy report message (matches the actual cron message format)
const message = `📊 *Monthly Analytics Report*
━━━━━━━━━━━━━━━━━━━━━━
🏪 *Medlife Pharmacy*
📅 *July 2026*
━━━━━━━━━━━━━━━━━━━━━━

💰 *Sales Overview*
• Total Sales: *₹2,45,680.00*
• Total Orders: *312*
• Avg. Order Value: *₹787.44*
• Total Discount Given: *₹12,340.00*

📈 *Estimated Profit (30% margin)*
• *₹73,704.00*
⚠️ _Please do not assume this as real profit. This is an estimate only, calculated at 30% margin on monthly sales._

🛡️ *Estimated Loss Saved from Medix*
• Near-Expiry Sold: *₹18,540.00* (42 items)
• Supplier Returns: *₹6,200.00* (8 items)
• *Total Saved: ₹24,740.00* (50 items)
• Items Currently At-Risk: *12*

━━━━━━━━━━━━━━━━━━━━━━
🤖 _Auto-generated by Medix POS_
_This is a TEST report._`;

const client = new Client({
    authStrategy: new LocalAuth({
        dataPath: './.wwebjs_auth'
    }),
    puppeteer: {
        headless: true,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-gpu',
            '--single-process'
        ]
    }
});

client.on('qr', (qr) => {
    console.log('\n⚡ Scan this QR code with your WhatsApp:\n');
    qrcode.generate(qr, { small: true });
});

client.on('authenticated', () => {
    console.log('✅ Authenticated!');
});

client.on('ready', async () => {
    console.log('✅ WhatsApp client ready!');
    console.log(`📤 Sending test message to ${PHONE}...`);

    try {
        const isRegistered = await client.isRegisteredUser(CHAT_ID);
        if (!isRegistered) {
            console.error(`❌ ${PHONE} is NOT registered on WhatsApp.`);
            process.exit(1);
        }

        await client.sendMessage(CHAT_ID, message);
        console.log('✅ Message sent successfully!');
    } catch (err) {
        console.error('❌ Failed to send:', err.message);
    }

    // Give it a moment then exit
    setTimeout(() => {
        console.log('Done. Exiting...');
        process.exit(0);
    }, 3000);
});

client.on('auth_failure', (msg) => {
    console.error('❌ Auth failure:', msg);
    process.exit(1);
});

console.log('🔄 Initializing WhatsApp client...');
client.initialize();
